---

- hosts: localhost
  connection: local
  become: yes

  vars:
    # See telegraf inputs for more plugings https://github.com/influxdata/telegraf/tree/master/plugins/inputs
    # Like https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response for tcp port checks
    telegraf_plugins_extra:
      - plugin: processes
      - plugin: kernel
      - plugin: linux_sysctl_fs
      - plugin: conntrack

  roles:
    - {role: cycloid.telegraf, tags: telegraf}
    - {role: geerlingguy.docker, tags: docker}
    - role: cycloid.ecs
      ecs_config: true
      ecs_cluster: "{{ project }}-ecs-cluster-{{ env }}"
      tags: ecs, ecs-agent

