- src: https://github.com/cycloidio/ansible-telegraf
  version: master
  name: cycloid.telegraf
  scm: git

- src: https://github.com/dj-wasabi/ansible-telegraf
  version: master
  name: dj-wasabi.telegraf
  scm: git

- src: https://github.com/cycloidio/ansible-ecs
  version: master
  name: cycloid.ecs
  scm: git

- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: geerlingguy.docker
  scm: git

- src: https://github.com/cycloidio/ansible-systemd
  version: master
  name: cycloid.systemd
  scm: git

